[NVD]
api_key=""
requests_per_delay="30"
request_delay="20"

[DT]
url=
key=

[GLOBAL]
score_system_ver=4.0
# Should the tool ignore CVE's marked as deferred
ignore_defferred=True
include_zero_vuln_components=False
validate_remote_certificate=True
source_locations=osv,nvd
verbose_logging=True

[TEMPLATE]
template="template/template_cvss4.xlsm"
template_start_row=3
template_sheet_name="Risk Assessment"
# (optional) Max lenght of the description when written into the template
template_max_description_char=50
# (optional) Should the CVSS Vector be split into individual parts and made available in the template?
split_cvss_score=False
# (optional) Column locations (1 based) where NVD data should be written on each row
column_id_description=B
column_id_cpe=C
column_id_bom=D
column_id_cve=E
column_id_publish_date=F
column_id_cvss=G
column_id_is_kev=T
column_id_epss=U
column_id_base_score=H
# (optional) Additional Column Values (static) to add to each row.
column_static_1_id=V
column_static_2_id=AH
column_static_3_id=AL
# Initial / Base
column_static_4_id=J
column_static_5_id=K
column_static_6_id=L
column_static_7_id=M
column_static_8_id=N
column_static_9_id=O
column_static_10_id=P
column_static_11_id=Q
column_static_12_id=R
column_static_13_id=S
column_static_14_id=T
# Residuals
column_static_15_id=X
column_static_16_id=Y
column_static_17_id=Z
column_static_18_id=AA
column_static_19_id=AB
column_static_20_id=AC
column_static_21_id=AD
column_static_22_id=AE
column_static_23_id=AF
column_static_24_id=AG
column_static_25_id=AH
# Risky Testing One
column_static_26_id=AJ