[SYSTEM_ID_1]
name="System 1"
boms="sbom.json"
# Valid formats are csv and json (CycloneDX)
bom_format=json
# Valid for CSV only
bom_cpe_column=1
# (optional) Combine all the BOMs into a single worksheet in the excel file
combine_all_boms=True
