[NVD]
api_key=""
requests_per_delay="30"
request_delay="20"

[DT]
url=
key=

[GLOBAL]
score_system_ver=3.1
# Should the tool ignore CVE's marked as deferred
ignore_defferred=True
include_zero_vuln_components=False
validate_remote_certificate=True
source_locations=osv,nvd
verbose_logging=True

[TEMPLATE]
template="template/template_cvss3.xlsm"
template_start_row=3
# (optional) Max lenght of the description when written into the template
template_max_description_char=50
# (optional) Should the CVSS Vector be split into individual parts and made available in the template?
split_cvss_score=True
# (optional) Column locations (1 based) where NVD data should be written on each row
column_id_bom=B
column_id_cpe=C
column_id_cve=D
column_id_description=E
column_id_publish_date=F
column_id_cvss=G
column_id_is_kev=H
column_id_epss=I
column_id_base_score=J
# (optional) If the base CVSS score should be split into individual elements specify the details here
column_split_cvss_av=N
column_split_cvss_ac=O
column_split_cvss_pr=P
column_split_cvss_ui=Q
column_split_cvss_s=R
column_split_cvss_c=S
column_split_cvss_i=T
column_split_cvss_a=U
# (optional) Additional Column Values (static) to add to each row.
column_static_1_id=W
#column_static_1_value="=GET_CVSS(M{row}, N{row}, O{row}, P{row}, Q{row}, R{row}, S{row}, T{row})"
column_static_2_id=V
#column_static_2_value='="CVSS:3.0/AV:"&_xlfn.IFS(N{row}="Network","N",N{row}="Adjacent","A",N{row}="Local","L",N{row}="Physical","P")&"/AC:"&LEFT(O{row},1)&"/PR:"&LEFT(P{row},1)&"/UI:"&IF(Q{row}="None","N","R")&"/S:"&LEFT(R{row},1)&"/C:"&LEFT(S{row},1)&"/I:"&LEFT(T{row},1)&"/A:"&LEFT(U{row},1)'
column_static_3_id=Y
#column_static_3_value="=INDEX('Notes'!G4:J7,_xlfn.IFS(W{row}>='Notes'!F4,1,W{row}>='Notes'!F5,2,W{row}>='Notes'!F6,3,W{row}<'Notes'!F6,4),MATCH(X{row},'Notes'!G3:J3,0))"
